version: '3.8'

services:
  db:
    image: postgres:15
    container_name: smartcheck_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: SmartCheck
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./APIserver/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: ./APIserver
    container_name: smartcheck_api
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_NAME: SmartCheck
    depends_on:
      - db

  admin:
    build: ./AdminPanel
    container_name: smartcheck_admin
    ports:
      - "8080:8080"
    depends_on:
      - app

volumes:
  postgres_data: